shell = "zsh"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.starship]
inline = 'eval "$(starship init zsh)"'

[plugins.fzf-tab]
github = "Aloxaf/fzf-tab"
[plugins.fzf-source]
inline = '''
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f /usr/share/doc/fzf/examples/key-bindings.zsh ] && source /usr/share/doc/fzf/examples/key-bindings.zsh
[ -f /usr/share/doc/fzf/examples/completion.zsh ] && source /usr/share/doc/fzf/examples/completion.zsh
'''

[plugins.zsh-syntax-highlighting]
# Recommended the last one
github = "zsh-users/zsh-syntax-highlighting"