[font]
normal = { family = "JetBranins Nerd Font", style = "Regular" }
size = 10.0

[window]
opacity = 0.9

[terminal]
shell = { program = "/usr/bin/zsh", args = ["-l", "-c", "tmux a -t 0 || tmux"] }

[scrolling]
history = 100000
multiplier = 5
